config:
  keywords:
    - BETA AR PANTS
    - BETA SL
  delay: 60
  webhook: ENTER WEBHOOK
  url: https://www.usedgear.arcteryx.com
  twitter:
    enabled: False
    consumer_key: ENTER CONSUMER KEY
    consumer_secret: ENTER CONSUMER SECRET
    access_token: ENTER ACCESS TOKEN
    access_token_secret: ENTER ACCESS SECRET